import Link from "next/link";
import MascotHero from "@/components/MascotHero";
import { ProcessSteps, TrustStrip } from "@/components/SectionBlocks";
import WhatsAppLeadForm from "@/components/WhatsAppLeadForm";
import Faq from "@/components/Faq";

const pics = ["Moderne Lichtinstallation","Sicherungskasten-Upgrade","Steckdosen & Schalter","Fehlerdiagnose vor Ort"];

export default function Page(){return <main className="gradient"><section className="section grid items-center gap-10 py-14 md:grid-cols-2"><div><h1 className="text-4xl font-black md:text-6xl">Mr Spark — Elektriker & Elektro-Notdienst</h1><p className="mt-4 text-lg text-slate-700">Schnelle Hilfe für Reparaturen, Elektroinstallation, Sicherungskasten und Störung beheben – zuverlässig, freundlich und professionell.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/de/notdienst" className="rounded-full bg-sky-600 px-5 py-3 font-semibold text-white">Notdienst anfragen</Link><Link href="/de/kontakt" className="rounded-full bg-amber-300 px-5 py-3 font-semibold">WhatsApp starten</Link><Link href="/de/preise" className="rounded-full border border-sky-300 px-5 py-3 font-semibold">Preise ansehen</Link></div></div><MascotHero compact={false} /></section><TrustStrip /><section className="section py-12"><h2 className="text-3xl font-bold">Elektrik-Bildwelt & Einsatzbereiche</h2><div className="mt-6 grid gap-4 md:grid-cols-4">{pics.map((p,i)=><article key={p} className="card overflow-hidden p-0"><div className={`h-36 ${["bg-gradient-to-br from-sky-200 to-cyan-100","bg-gradient-to-br from-amber-100 to-orange-100","bg-gradient-to-br from-blue-100 to-indigo-100","bg-gradient-to-br from-cyan-100 to-emerald-100"][i]}`} /><div className="p-4"><h3 className="font-semibold">{p}</h3><p className="mt-1 text-sm text-slate-600">Saubere Umsetzung mit Sicherheitsfokus und klaren Arbeitsschritten.</p></div></article>)}</div></section><section className="section py-12"><h2 className="text-3xl font-bold">Leistungen</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{["Elektriker","Elektroinstallation","Elektro-Notdienst","Sicherungskasten","Steckdosen & Licht","Störung beheben"].map(s=><article key={s} className="card"><h3 className="text-xl font-semibold">{s}</h3><p className="mt-2 text-slate-700">Professionelle Durchführung mit transparentem Ablauf und sauberer Kommunikation.</p></article>)}</div></section><ProcessSteps /><section className="section py-10"><div className="rounded-3xl bg-rose-50 p-6"><h2 className="text-2xl font-bold">Akute Elektro-Probleme?</h2><p className="mt-2">Stromausfall, Kurzschluss, FI-Schalter löst aus, Brandgeruch oder Sicherungskasten Probleme: wir koordinieren schnelle Hilfe.</p></div></section><Faq items={[{q:"Wie schnell kommt ein Elektriker?",a:"Bei Notfällen priorisieren wir sofortige Rückmeldung und schnellstmögliche Einsatzplanung."},{q:"Gibt es 24h Notdienst?",a:"Ja, wir bieten rund um die Uhr Erreichbarkeit für elektrische Notfälle."}]} /><section className="section py-12"><h2 className="text-3xl font-bold">Kontakt per WhatsApp</h2><div className="mt-6 grid gap-6 md:grid-cols-2"><WhatsAppLeadForm sourcePage="/de" /><MascotHero compact flipped /></div></section></main>}
