"use client";
import Link from "next/link";
import Image from "next/image";
import { usePathname } from "next/navigation";
import LanguageSelector from "@/components/LanguageSelector";

const de=[["Startseite","/de"],["Leistungen","/de/leistungen"],["Elektriker","/de/elektriker"],["Elektro","/de/elektro"],["Notdienst","/de/notdienst"],["Einsatzgebiet","/de/einsatzgebiet"],["Preise","/de/preise"],["Kontakt","/de/kontakt"]];
const en=[["Home","/en"],["Services","/en/leistungen"],["Electrician","/en/elektriker"],["Electrical","/en/elektro"],["Emergency","/en/notdienst"],["Coverage","/en/einsatzgebiet"],["Pricing","/en/preise"],["Contact","/en/kontakt"]];

export function Header(){const p=usePathname()||"/de"; const isEn=p.startsWith('/en'); const links=isEn?en:de; const base=isEn?'/en':'/de'; return <header className="sticky top-0 z-50 border-b border-sky-100 bg-white/95 backdrop-blur"><div className="section flex min-h-20 flex-wrap items-center justify-between gap-3 py-3"><Link href={base} className="shrink-0"><Image src="/brand/mr-spark-logo.svg" alt="Mr Spark" width={260} height={48} className="h-auto w-[220px] md:w-[260px]"/></Link><nav className="hidden gap-4 xl:flex">{links.map(([label,href])=><Link key={href} href={href} className="text-sm font-semibold text-slate-700 hover:text-sky-700">{label}</Link>)}</nav><div className="flex items-center gap-2"><LanguageSelector/><Link href={`${base}/notdienst`} className="rounded-full bg-sky-600 px-3 py-2 text-xs font-semibold text-white md:text-sm">{isEn?'24h Emergency':'24h Notdienst'}</Link><Link href={`${base}/kontakt`} className="rounded-full bg-amber-300 px-3 py-2 text-xs font-semibold text-slate-900 md:text-sm">{isEn?'Start Telegram':'Telegram starten'}</Link></div></div></header>}
export function Footer(){return <footer className="mt-16 border-t border-sky-100 bg-white"><div className="section grid gap-8 py-12 md:grid-cols-4"><div><h3 className="text-xl font-bold text-sky-700">Mr Spark</h3><p className="mt-2 text-slate-600">Elektriker & Elektro-Notdienst für schnelle, sichere Hilfe.</p></div><div><h4 className="font-semibold">Leistungen</h4><ul className="mt-2 space-y-1 text-slate-600"><li>Elektroinstallation</li><li>Sicherungskasten</li><li>Steckdosen & Licht</li></ul></div><div><h4 className="font-semibold">Notfall</h4><p className="mt-2 text-slate-600">24h erreichbar bei Stromausfall, Kurzschluss oder FI-Problemen.</p></div><div><h4 className="font-semibold">Rechtliches</h4><ul className="mt-2 space-y-1 text-slate-600"><li><Link href="/de/impressum">Impressum</Link></li><li><Link href="/de/datenschutz">Datenschutz</Link></li></ul></div></div></footer>}
